### ISSUE TITLE
Making it run for a specific token

### ISSUE THREAD

**Issue by moonsoonexpress** [gatotbima1104/wallet-scrapper-dexscreener#1]
Hey man, great job with this script. 

How can you make it run for a specific token address? 

I m looking for a solution to grab top X traders of a specific token. 

Thanks in advance!

**Comment by gatotbima1104** [comment]
Yeah, you can customize it using last ednpoint of the token like :
{bla-bla}/token

and make sure to handle the open and last web, for making it more dynamic entering each token iteration
